// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { access, readFile, readdir, symlink, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import test from 'node:test';
import ts from 'typescript';
import { compare, compareFragments, fragments, pairedFiles } from './compare.mjs';
import { generate, prepare } from './Matched/prepare.mjs';
import { directory } from './reference.mjs';

const output = await generate();
const ledger = JSON.parse(await readFile(join(directory, 'Matched/allowances.json')));

test('production arc-gen output compares file-by-file against untouched pinned C# captures', async () => {
    await compare(output);
});

test('every API fragment and every exact allowance rejects a new difference', async () => {
    for (const file of pairedFiles) {
        const csharp = fragments(await readFile(join(directory, 'Snapshots/Primary22.48.2', file)), 'csharp');
        const go = fragments(await readFile(join(output, file)), 'go');
        for (const key of Object.keys(go)) {
            assert.throws(() => compareFragments(file, csharp, { ...go, [key]: go[key] + ' unexpected' }, ledger.allowances), /Unapproved difference/);
        }
        assert.throws(() => compareFragments(file, csharp, { ...go, extraField: 'id : number' }, ledger.allowances), /Unapproved difference/);
        const allowance = ledger.allowances.find(entry => entry.file === file);
        if (allowance) {
            assert.throws(() => compareFragments(file, csharp, go, ledger.allowances.filter(entry => entry !== allowance)), /Unapproved difference/);
            assert.throws(() => compareFragments(file, csharp, go, [...ledger.allowances, allowance]), /difference|Stale or duplicate/);
        }
    }
});

test('unexpected output cannot be ignored by the inventory comparison', async () => {
    const extra = join(output, 'user.ts');
    await writeFile(extra, 'export const unexpected = true;\n');
    await assert.rejects(() => compare(output), /deep-equal/);
});

test('comments and trailing tokens are not blanket-normalized away', () => {
    const original = Buffer.from('// Code generated by arc-gen TypeScript models; DO NOT EDIT.\nexport class Model { id!: string; }\n');
    const commented = Buffer.from(original.toString().replace('id!', '// extra\n id!') + '// trailing\n');
    assert.notDeepEqual(fragments(original, 'go'), fragments(commented, 'go'));
    assert.notDeepEqual(fragments(original, 'go'), fragments(Buffer.from(original.toString().replace('id!', 'other!')), 'go'));
});

test('complete identity-free C# equivalent Observe fails explicitly without partial publication', async () => {
    const { consumer, tools, go } = await prepare({ observable: true });
    const before = await readFile(join(consumer, 'input.go'));
    const result = spawnSync(go, ['run', './cmd/arc-gen', '-dir', consumer, '-config', join(consumer, 'profile.json'), '.'],
        { cwd: tools, encoding: 'utf8', timeout: 60000, maxBuffer: 10 * 1024 * 1024 });
    assert.equal(result.error, undefined, result.error?.message);
    assert.equal(result.status, 1, result.stdout + result.stderr);
    assert.match(result.stderr, /observable collection requires one unambiguous conventional identity member ID\/Id, including JSON-hidden and embedded members/);
    assert.deepEqual(await readFile(join(consumer, 'input.go')), before);
    await assert.rejects(() => access(join(consumer, 'web')), { code: 'ENOENT' });
    assert.deepEqual((await readdir(consumer)).sort(), ['go.mod', 'go.sum', 'input.go', 'observable.go', 'profile.json']);
});

test('live Go output compiles strictly against the pinned real client packages', async () => {
    const nodeModules = join(directory, 'node_modules');
    // Normal package resolution must honor the packages' export maps, not load
    // their uncompiled source trees through a wildcard paths mapping.
    await symlink(nodeModules, join(output, '../node_modules'), 'dir');
    const program = ts.createProgram(pairedFiles.map(file => join(output, file)), {
        target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext, moduleResolution: ts.ModuleResolutionKind.Bundler,
        strict: true, skipLibCheck: false, noEmit: true, types: ['node'],
        typeRoots: [join(nodeModules, '@types')]
    });
    const diagnostics = ts.getPreEmitDiagnostics(program);
    assert.equal(diagnostics.length, 0, ts.formatDiagnosticsWithColorAndContext(diagnostics, {
        getCurrentDirectory: () => directory, getCanonicalFileName: file => file, getNewLine: () => '\n'
    }));
});
