// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
import assert from 'node:assert/strict';
import { readFile, symlink, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import test from 'node:test';
import ts from 'typescript';
import { compare, compareFragments, fragments, pairedFiles } from './compare.mjs';
import { generate } from './Matched/prepare.mjs';
import { directory, run } from './helpers.mjs';

const output = await generate();
const ledger = JSON.parse(await readFile(join(directory, 'Matched/allowances.json')));

test('production arc-gen output compares file-by-file against untouched pinned C# captures', async () => {
    await compare(output);
});

test('generation and check ignore inherited workspace and toolchain overrides', async () => {
    const generated = run(process.execPath, [join(directory, 'Matched/prepare.mjs')], directory, {
        ...process.env,
        GOWORK: join(output, 'missing.go.work'),
        GOTOOLCHAIN: 'invalid-toolchain'
    }).trim();
    await compare(generated);
});

test('every API fragment and every exact allowance rejects a new difference', async () => {
    for (const file of pairedFiles) {
        const csharp = fragments(await readFile(join(directory, 'Snapshots/Primary22.48.2', file)), 'csharp');
        const go = fragments(await readFile(join(output, file)), 'go');
        for (const key of Object.keys(go)) {
            assert.throws(() => compareFragments(file, csharp, { ...go, [key]: go[key] + ' unexpected' }, ledger.allowances), /Unapproved difference/);
        }
        assert.throws(() => compareFragments(file, csharp, { ...go, extraField: 'id : number' }, ledger.allowances), /Unapproved difference/);
        const allowance = ledger.allowances.find(entry => entry.file === file);
        if (allowance) {
            assert.throws(() => compareFragments(file, csharp, go, ledger.allowances.filter(entry => entry !== allowance)), /Unapproved difference/);
            assert.throws(() => compareFragments(file, csharp, go, [...ledger.allowances, allowance]), /difference|Stale or duplicate/);
        }
    }
});

test('unexpected output cannot be ignored by the inventory comparison', async () => {
    const extra = join(output, 'user.ts');
    await writeFile(extra, 'export const unexpected = true;\n');
    await assert.rejects(() => compare(output), /deep-equal/);
});

test('comments and trailing tokens are not blanket-normalized away', () => {
    const original = Buffer.from('// Code generated by arc-gen TypeScript models; DO NOT EDIT.\nexport class Model { id!: string; }\n');
    const commented = Buffer.from(original.toString().replace('id!', '// extra\n id!') + '// trailing\n');
    assert.notDeepEqual(fragments(original, 'go'), fragments(commented, 'go'));
    assert.notDeepEqual(fragments(original, 'go'), fragments(Buffer.from(original.toString().replace('id!', 'other!')), 'go'));
});

test('live Go output compiles strictly against the pinned real client packages', async () => {
    const nodeModules = join(directory, 'node_modules');
    // Normal package resolution must honor the packages' export maps, not load
    // their uncompiled source trees through a wildcard paths mapping.
    await symlink(nodeModules, join(output, '../node_modules'), 'dir');
    const program = ts.createProgram(pairedFiles.map(file => join(output, file)), {
        target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext, moduleResolution: ts.ModuleResolutionKind.Bundler,
        strict: true, skipLibCheck: false, noEmit: true, types: ['node'],
        typeRoots: [join(nodeModules, '@types')]
    });
    const diagnostics = ts.getPreEmitDiagnostics(program);
    assert.equal(diagnostics.length, 0, ts.formatDiagnosticsWithColorAndContext(diagnostics, {
        getCurrentDirectory: () => directory, getCanonicalFileName: file => file, getNewLine: () => '\n'
    }));
});
