// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import ts from 'typescript';
import { directory, filesIn, stableBytes } from './reference.mjs';

export const pairedFiles = ['All', 'Detail', 'Listing', 'Notice', 'Register', 'Status', 'UrgentNotice', 'index']
    .map(name => `ProxyComparison/${name}.ts`);
const csharpBanner = '/*---------------------------------------------------------------------------------------------\n *  **DO NOT EDIT** - This file is an automatically generated file.\n *--------------------------------------------------------------------------------------------*/';
const prologueComments = ['/* eslint-disable sort-imports */', '/* eslint-disable @typescript-eslint/no-empty-interface */',
    '// eslint-disable-next-line header/header'];

// Normalize whitespace and quote spelling only, retaining comments, token kinds,
// literals and punctuation. No identifier, field, import or API is ignored.
function tokens(text) {
    const scanner = ts.createScanner(ts.ScriptTarget.Latest, false, ts.LanguageVariant.Standard, text);
    const result = [];
    for (let kind = scanner.scan(); kind !== ts.SyntaxKind.EndOfFileToken; kind = scanner.scan()) {
        if (kind === ts.SyntaxKind.WhitespaceTrivia || kind === ts.SyntaxKind.NewLineTrivia) continue;
        result.push(kind === ts.SyntaxKind.StringLiteral ? JSON.stringify(scanner.getTokenValue()) : scanner.getTokenText());
    }
    return result.join(' ');
}

export function fragments(bytes, language) {
    let text = bytes.toString();
    if (language === 'csharp') {
        text = stableBytes(bytes).toString();
        if (text.startsWith('// @generated by Cratis.')) {
            text = text.slice(text.indexOf('\n') + 1).trimStart();
            assert.ok(text.startsWith(csharpBanner), 'Unknown C# generated banner');
            text = text.slice(csharpBanner.length).trimStart();
            for (const comment of prologueComments) {
                if (text.startsWith(comment)) text = text.slice(comment.length).trimStart();
            }
        }
    } else {
        assert.match(text, /^\/\/ Code generated by arc-gen TypeScript (models|commands|queries); DO NOT EDIT\.\n/);
        text = text.slice(text.indexOf('\n') + 1);
    }
    const source = ts.createSourceFile('proxy.ts', text, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
    assert.deepEqual(source.parseDiagnostics, [], 'Invalid generated TypeScript');
    const parts = {};
    const put = (key, value) => {
        assert.ok(!Object.hasOwn(parts, key), `Duplicate fragment ${key}`);
        parts[key] = value;
    };
    const order = [];
    const imports = [];
    for (const statement of source.statements) {
        if (ts.isImportDeclaration(statement)) {
            assert.equal(order.length, 0, 'Imports must precede declarations');
            imports.push(statement.getFullText(source));
            continue;
        }
        const key = statement.name?.text || (ts.isExportDeclaration(statement) ? `export:${statement.moduleSpecifier.text}` : `statement:${order.length}`);
        order.push(key);
        if (!ts.isClassDeclaration(statement)) { put(key, tokens(statement.getFullText(source))); continue; }
        put(`${key}:header`, tokens(text.slice(statement.getFullStart(), statement.members.pos)));
        const memberOrder = [];
        for (const member of statement.members) {
            const memberKey = `${member.modifiers?.some(modifier => modifier.kind === ts.SyntaxKind.StaticKeyword) ? 'static:' : ''}${ts.SyntaxKind[member.kind]}:${member.name?.getText(source) || 'constructor'}`;
            memberOrder.push(memberKey);
            put(`${key}:${memberKey}`, tokens(member.getFullText(source)));
        }
        put(`${key}:order`, JSON.stringify(memberOrder));
        put(`${key}:footer`, tokens(text.slice(statement.members.end, statement.end)));
    }
    put('imports', tokens(imports.join('\n')));
    put('order', JSON.stringify(order));
    put('trailer', tokens(source.endOfFileToken.getFullText(source)));
    return parts;
}

export function compareFragments(file, csharp, go, allowances) {
    const relevant = allowances.filter(entry => entry.file === file);
    const keys = [...new Set([...Object.keys(csharp), ...Object.keys(go)])].sort();
    const used = new Set();
    for (const key of keys) {
        const before = csharp[key] ?? null;
        const after = go[key] ?? null;
        if (before === after) continue;
        const matches = relevant.filter(entry => entry.fragment === key && entry.csharp === before && entry.go === after);
        assert.equal(matches.length, 1, `Unapproved difference ${file} / ${key}\nC#: ${before}\nGo: ${after}`);
        assert.ok(matches[0].reason?.trim(), 'Allowance requires an explanation');
        used.add(matches[0]);
    }
    assert.equal(used.size, relevant.length, `Stale or duplicate allowance in ${file}`);
    return used.size;
}

export async function compare(output) {
    // Observe is intentionally NOT treated as an allowed missing output. This is
    // the eight-file admitted subset; the full nine-file fixture remains blocked.
    assert.deepEqual(await filesIn(output), ['.arc-gen-manifest.json', ...pairedFiles]);
    const ledger = JSON.parse(await readFile(join(directory, 'Matched/allowances.json')));
    assert.equal(ledger.formatVersion, 1);
    assert.ok(ledger.allowances.every(entry => pairedFiles.includes(entry.file)), 'Unknown allowance file');
    const provenance = JSON.parse(await readFile(join(directory, 'provenance.json')));
    assert.equal(provenance.inputs.authority.commit, '7c1e78075b737df64f69fddfaae83374f75e3612');
    assert.equal(provenance.inputs.dotnet.version, '22.48.2');
    assert.equal(createHash('sha256').update(await readFile(join(directory, 'reference/Fixtures.cs'))).digest('hex'),
        provenance.inputs.precedent.sourceSha256, 'Pinned C# source changed');
    let count = 0;
    for (const file of pairedFiles) {
        const bytes = stableBytes(await readFile(join(directory, 'Snapshots/Primary22.48.2', file)));
        assert.equal(createHash('sha256').update(bytes).digest('hex'), provenance.snapshots[file], `C# snapshot changed: ${file}`);
        count += compareFragments(file, fragments(bytes, 'csharp'), fragments(await readFile(join(output, file)), 'go'), ledger.allowances);
    }
    console.log(`Go/C# admitted subset: ${pairedFiles.length} files compared, ${count} exact fragment allowances; Observe remains blocked.`);
}
