// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readdir } from 'node:fs/promises';
import { join } from 'node:path';

export const directory = import.meta.dirname;
export const sha256 = bytes => createHash('sha256').update(bytes).digest('hex');

export function run(command, args, cwd = directory, env = process.env, timeout = 60000) {
    const child = spawnSync(command, args, { cwd, env, encoding: 'utf8', timeout, maxBuffer: 10 * 1024 * 1024 });
    assert.equal(child.error, undefined, child.error?.message);
    assert.equal(child.status, 0, `${command} ${args.join(' ')}\n${child.stdout}\n${child.stderr}`);
    return child.stdout;
}

// Normalize only the timestamp. Every C# body and its supplied SHA-256 remain unchanged.
export function stableBytes(bytes) {
    const end = bytes.indexOf(10);
    const header = bytes.subarray(0, end).toString();
    if (!header.startsWith('// @generated by Cratis.')) return bytes;
    assert.match(header, /^\/\/ @generated by Cratis\. Source: .*\. Time: (?:\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{7}Z|<timestamp>)\. Hash: [A-F0-9]{64}$/);
    assert.equal(header.slice(-64), sha256(bytes.subarray(end + 1)).toUpperCase(), 'Invalid C# provenance body hash');
    return Buffer.concat([Buffer.from(header.replace(/Time: .*?\. Hash:/, 'Time: <timestamp>. Hash:')), bytes.subarray(end)]);
}

export async function filesIn(path, prefix = '') {
    const files = [];
    for (const entry of await readdir(path, { withFileTypes: true })) {
        assert.ok(entry.isFile() || entry.isDirectory(), `Unexpected output ${entry.name}`);
        const name = prefix + entry.name;
        if (entry.isDirectory()) files.push(...await filesIn(join(path, entry.name), name + '/'));
        else files.push(name);
    }
    return files.sort();
}
