// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { access, mkdir, mkdtemp, readFile, readdir, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

export const directory = import.meta.dirname;
const sha256 = bytes => createHash('sha256').update(bytes).digest('hex');
const expectedFiles = ['All.ts', 'Detail.ts', 'Listing.ts', 'Notice.ts', 'Observe.ts', 'Register.ts', 'Status.ts', 'UrgentNotice.ts', 'index.ts'].map(name => `ProxyComparison/${name}`);
const options = ['0'];

export function run(command, args, cwd = directory) {
    const child = spawnSync(command, args, { cwd, encoding: 'utf8', timeout: 60000, maxBuffer: 10 * 1024 * 1024 });
    assert.equal(child.error, undefined, child.error?.message);
    assert.equal(child.status, 0, `${command} ${args.join(' ')}\n${child.stdout}\n${child.stderr}`);
    return child.stdout;
}

// Normalize only the timestamp. Every C# body and its supplied SHA-256 remain unchanged.
export function stableBytes(bytes) {
    const end = bytes.indexOf(10);
    const header = bytes.subarray(0, end).toString();
    if (!header.startsWith('// @generated by Cratis.')) return bytes;
    assert.match(header, /^\/\/ @generated by Cratis\. Source: .*\. Time: (?:\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{7}Z|<timestamp>)\. Hash: [A-F0-9]{64}$/);
    assert.equal(header.slice(-64), sha256(bytes.subarray(end + 1)).toUpperCase(), 'Invalid C# provenance body hash');
    return Buffer.concat([Buffer.from(header.replace(/Time: .*?\. Hash:/, 'Time: <timestamp>. Hash:')), bytes.subarray(end)]);
}

export async function filesIn(path, prefix = '') {
    const files = [];
    for (const entry of await readdir(path, { withFileTypes: true })) {
        assert.ok(entry.isFile() || entry.isDirectory(), `Unexpected output ${entry.name}`);
        const name = prefix + entry.name;
        if (entry.isDirectory()) files.push(...await filesIn(join(path, entry.name), name + '/'));
        else files.push(name);
    }
    return files.sort();
}

export async function reference({ capture = false } = {}) {
    assert.equal(process.version, 'v26.8.1', 'Use the pinned Node patch');
    assert.equal(run('npm', ['--version']).trim(), '12.0.2', 'Use the pinned npm version');
    const project = join(directory, 'reference');
    const source = await readFile(join(project, 'Fixtures.cs'));
    assert.equal(sha256(source), '0bc99230d0f89b556c7f5d90d725533252b9ace8d6a22ae411cfcc95197213a1', 'Imported fixture changed');
    const lockBytes = await readFile(join(project, 'packages.lock.json'));
    const lock = JSON.parse(lockBytes);
    const assets = JSON.parse(await readFile(join(project, 'obj/project.assets.json')));
    for (const name of ['Cratis.Arc', 'Cratis.Arc.ProxyGenerator.Build']) {
        const locked = lock.dependencies['net10.0'][name];
        assert.equal(locked.resolved, '22.48.2');
        assert.equal(locked.requested, '[22.48.2, 22.48.2]');
        assert.equal(assets.libraries[`${name}/${locked.resolved}`].sha512, locked.contentHash, `Unlocked restored package ${name}`);
    }
    const dependency = lock.dependencies['net10.0']['Cratis.Arc.ProxyGenerator.Build'];
    assert.equal(dependency.resolved, '22.48.2');
    assert.equal(dependency.requested, '[22.48.2, 22.48.2]');
    const library = assets.libraries['Cratis.Arc.ProxyGenerator.Build/22.48.2'];
    assert.equal(library.sha512, dependency.contentHash);
    const executableRelative = 'tasks/net10.0/Cratis.Arc.ProxyGenerator.Build.dll';
    let executable;
    for (const folder of Object.keys(assets.packageFolders)) {
        const candidate = join(folder, library.path, executableRelative);
        try { await access(candidate); executable = candidate; break; }
        catch (error) { if (error.code !== 'ENOENT') throw error; }
    }
    assert.ok(executable, 'Run dotnet restore --locked-mode first');
    const sdk = run('dotnet', ['--version'], project).trim();
    assert.equal(sdk, '10.0.401');
    const npmLockBytes = await readFile(join(directory, 'package-lock.json'));
    const npmLock = JSON.parse(npmLockBytes);
    const clients = {};
    for (const [name, version] of Object.entries({ '@cratis/arc': '22.48.2', '@cratis/arc.react': '22.48.2', '@cratis/fundamentals': '7.22.0', react: '18.3.1', 'react-dom': '18.3.1' })) {
        const entry = npmLock.packages['node_modules/' + name];
        assert.equal(entry.version, version);
        assert.ok(entry.integrity);
        clients[name] = { version, integrity: entry.integrity };
    }
    const inputs = {
        authority: { repository: 'https://github.com/Cratis/Arc', commit: '7c1e78075b737df64f69fddfaae83374f75e3612' },
        precedent: { repository: 'https://github.com/Cratis/Arc.TypeScript', commit: '2f546a89c35d49726b78ed2bf573fff8d77b056e', source: 'ContractTests/DotNET/ProxyComparison/Fixtures.cs', sourceSha256: sha256(source), historicalVersion: '22.45.0' },
        dotnet: { sdk, package: 'Cratis.Arc.ProxyGenerator.Build', version: dependency.resolved, packageSha512: dependency.contentHash, executable: executableRelative, executableSha256: sha256(await readFile(executable)), input: 'reference/bin/Release/net10.0/Arc.Go.ProxyComparison.dll', options, optionsSha256: sha256(JSON.stringify(options)), lockSha256: sha256(lockBytes), projectSha256: sha256(await readFile(join(project, 'Reference.csproj'))) },
        frontend: { node: '26.8.1', npm: '12.0.2', clients, lockSha256: sha256(npmLockBytes) }
    };
    const snapshots = join(directory, 'Snapshots/Primary22.48.2');
    if (!capture) {
        const recorded = JSON.parse(await readFile(join(directory, 'provenance.json')));
        assert.deepEqual(recorded.inputs, inputs, 'Reference inputs changed; restore/build and recapture through the pinned generator');
    }
    const work = process.env.AI_WORK_OUTPUT || join(directory, '../../.ai-work/proxy-reference');
    await mkdir(work, { recursive: true });
    const output = await mkdtemp(join(work, 'reference-'));
    const log = run('dotnet', [executable, join(directory, inputs.dotnet.input), output, ...options], project);
    process.stdout.write(log);
    assert.deepEqual(await filesIn(output), expectedFiles, 'Pinned C# output inventory changed');
    const hashes = {};
    const rendered = [];
    for (const name of expectedFiles) {
        const bytes = stableBytes(await readFile(join(output, name)));
        hashes[name] = sha256(bytes);
        rendered.push([name, bytes]);
        if (!capture) {
            assert.deepEqual(bytes, stableBytes(await readFile(join(snapshots, name))), `C# snapshot drift: ${name}`);
        }
    }
    if (capture) {
        // Capture is reachable only after successful executable generation and a complete inventory.
        for (const [name, bytes] of rendered) {
            await mkdir(join(snapshots, name, '..'), { recursive: true });
            await writeFile(join(snapshots, name), bytes);
        }
        await writeFile(join(directory, 'provenance.json'), JSON.stringify({ inputs, snapshots: hashes }, null, 2) + '\n');
    } else {
        assert.deepEqual(await filesIn(snapshots), expectedFiles);
        const recorded = JSON.parse(await readFile(join(directory, 'provenance.json')));
        assert.deepEqual(recorded.snapshots, hashes);
    }
    console.log(`Pinned C# reference: ${rendered.length} files verified; Go comparison not yet implemented.`);
}

if (process.argv[1] && pathToFileURL(resolve(process.argv[1])).href === import.meta.url) {
    assert.ok(process.argv.slice(2).every(arg => arg === '--capture'), 'Only --capture is supported');
    await reference({ capture: process.argv.includes('--capture') });
}
