// Code generated by arc-gen v0.1.0-dev (format v1); DO NOT EDIT.
// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

package generatedconsumerfixture

import (
	arcgencontext "context"
	arcgenfmt "fmt"
	arcgenarc "github.com/cratis/arc.go"
	arcgenexecution "github.com/cratis/arc.go/execution"
	arcgenmetadata "github.com/cratis/arc.go/metadata"
	arcgenobservable "github.com/cratis/arc.go/observable"
	arcgenqueries "github.com/cratis/arc.go/queries"
	arcgendependencyinjection "github.com/cratis/fundamentals.go/dependencyinjection"
)

// ArcBindings optionally supplies typed, stage-local dependencies without a container.
// Nil callbacks use execution.Resolve and declare their exact DI keys at registration.
// Callbacks are borrowed, may run concurrently, and must not retain the operation scope.
type ArcBindings struct {
	// ResolveItemFeed resolves github.com/cratis/arc.go/ContractTests/observables/generatedconsumerfixture.ItemFeed only when its execution stage is reached.
	ResolveItemFeed func(arcgencontext.Context, *arcgenexecution.Scope) (ItemFeed, error)
}

func (arcBindings ArcBindings) arcResolveItemFeed(arcCtx arcgencontext.Context, arcScope *arcgenexecution.Scope) (ItemFeed, error) {
	if arcBindings.ResolveItemFeed != nil {
		return arcBindings.ResolveItemFeed(arcCtx, arcScope)
	}
	return arcgenexecution.Resolve[ItemFeed](arcCtx, arcScope)
}

// RegisterArtifacts registers this package's artifacts through Arc's public registrars.
// Supply at most one binding set. Registration activates no business methods or services.
// Errors stop registration immediately; discard the builder after an error.
func RegisterArtifacts(arcBuilder *arcgenarc.Builder, bindings ...ArcBindings) error {
	if arcBuilder == nil || len(bindings) > 1 {
		return arcgenfmt.Errorf("arc-gen: expected a builder and at most one ArcBindings")
	}
	var arcBindings ArcBindings
	if len(bindings) == 1 {
		arcBindings = bindings[0]
	}
	if arcErr := arcgenqueries.RegisterReadModel[Item](arcBuilder, arcgenqueries.WithModelName("Item"), arcgenqueries.WithModelPath(""),
		arcgenqueries.WithModelNamespace("Contracts.Items"),
		arcgenqueries.WithModelAuthorization(arcgenmetadata.Authorization{AllowAnonymous: true}),
	); arcErr != nil {
		return arcErr
	}
	var arcKeys []arcgendependencyinjection.Key
	if arcBindings.ResolveItemFeed == nil {
		arcKeys = append(arcKeys, arcgendependencyinjection.KeyFor[ItemFeed]())
	}
	if arcErr := arcgenqueries.RegisterObservable[Item, Arguments, []Item](arcBuilder, "All", arcgenqueries.Invoke(func(arcCtx arcgencontext.Context, arcInv *arcgenqueries.Invocation, arcArgs Arguments) (arcgenobservable.Source[[]Item], error) {
		arcDependency, arcErr := arcBindings.arcResolveItemFeed(arcCtx, arcInv.Scope())
		if arcErr != nil {
			var arcZero arcgenobservable.Source[[]Item]
			return arcZero, arcErr
		}
		return (Item{}).All(arcCtx, arcArgs, arcDependency)
	}),
		arcgenqueries.WithPath[Arguments]("/items"),
		arcgenqueries.WithDependencies[Arguments](arcKeys...),
	); arcErr != nil {
		return arcErr
	}
	var arcKeys2 []arcgendependencyinjection.Key
	if arcBindings.ResolveItemFeed == nil {
		arcKeys2 = append(arcKeys2, arcgendependencyinjection.KeyFor[ItemFeed]())
	}
	if arcErr := arcgenqueries.RegisterObservable[Item, Arguments, []Item](arcBuilder, "Private", arcgenqueries.Invoke(func(arcCtx arcgencontext.Context, arcInv *arcgenqueries.Invocation, arcArgs Arguments) (arcgenobservable.Source[[]Item], error) {
		arcDependency2, arcErr := arcBindings.arcResolveItemFeed(arcCtx, arcInv.Scope())
		if arcErr != nil {
			var arcZero arcgenobservable.Source[[]Item]
			return arcZero, arcErr
		}
		return (Item{}).Private(arcCtx, arcArgs, arcDependency2)
	}),
		arcgenqueries.WithAuthorization[Arguments](arcgenmetadata.Authorization{AllowAnonymous: false, Requirements: []arcgenmetadata.AuthorizationRequirement{{Policy: "", Roles: []string{"Reader"}}}}),
		arcgenqueries.WithDependencies[Arguments](arcKeys2...),
	); arcErr != nil {
		return arcErr
	}
	if arcErr := arcBuilder.ExpectGeneratedEndpoints("adapter-only:9aea1d313e25f4861e72e26768d7f9c395b1a50bf1f8eb8a19a22f8d25cfff93", []arcgenmetadata.Endpoint{
		{Identity: "Contracts.Items.Item.All", Method: "GET", Path: "/items", ValidateOnly: false},
		{Identity: "Contracts.Items.Item.All", Method: "QUERY", Path: "/items", ValidateOnly: false},
		{Identity: "Contracts.Items.Item.Private", Method: "GET", Path: "/api/contracts/items/private", ValidateOnly: false},
		{Identity: "Contracts.Items.Item.Private", Method: "QUERY", Path: "/api/contracts/items/private", ValidateOnly: false},
	}); arcErr != nil {
		return arcErr
	}
	return nil
}
