// @generated by Cratis. Source: ProxyComparison.Status. Time: <timestamp>. Hash: 2021C7DF28DABBEC728CC5649211601AC22C9E7848AABC7C394B1DBBE4D65D34
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
export enum Status {
    draft = 0,
    published = 1,
}
