// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { registerHooks } from 'node:module';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import { Guid } from '@cratis/fundamentals';
import { QueryHttpMethod } from '@cratis/arc/queries';

const root = new URL('../../../.ai-work/output/ts-publication/', import.meta.url);
const modules = new Map(['@cratis/fundamentals', '@cratis/arc/commands', '@cratis/arc/queries',
    '@cratis/arc/reflection', '@cratis/arc.react/commands', '@cratis/arc.react/queries']
    .map(specifier => [specifier, import.meta.resolve(specifier)]));
registerHooks({ resolve(specifier, context, nextResolve) {
    if (modules.has(specifier)) return nextResolve(modules.get(specifier), context);
    if (specifier.startsWith('.') && context.parentURL?.includes('/ts-publication/tsc/')) {
        const candidate = new URL(specifier + '.js', context.parentURL);
        if (existsSync(fileURLToPath(candidate))) return nextResolve(candidate.href, context);
    }
    return nextResolve(specifier, context);
}});
const { Echo, Listing, All, Find } = await import(new URL('tsc/Tasks/index.js', root));
const { Detail, Status } = await import(new URL('tsc/Shared/index.js', root));

test('production CLI manifest agrees with complete generated bytes and inventory', () => {
    const output = new URL('consumer/web/', root);
    const manifest = JSON.parse(readFileSync(new URL('.arc-gen-manifest.json', output)));
    assert.equal(manifest.format, 1); assert.equal(manifest.owner, 'production-fixture');
    const files = readdirSync(output, { recursive: true, withFileTypes: true })
        .filter(item => item.isFile()).map(item => fileURLToPath(new URL(item.name, 'file://' + item.parentPath + '/')))
        .filter(path => path.endsWith('.ts')).sort();
    assert.equal(files.length, 8);
    assert.equal(manifest.files.length, 9);
    for (const file of manifest.files) {
        const base = file.root === 'go' ? new URL('consumer/', root) : output;
        const bytes = readFileSync(new URL(file.path, base));
        assert.match(bytes.toString(), /^\/\/ Code generated by arc-gen /);
        assert.equal(createHash('sha256').update(bytes).digest('hex'), file.hash);
    }
    assert.equal(existsSync(new URL('.arc-gen-pending.json', output)), false);
});

test('actual CLI-generated adapters and proxies execute commands and GET/QUERY snapshots', { timeout: 15000 }, async () => {
    const child = spawn(fileURLToPath(new URL('fixture-host', root)), [], { stdio: ['ignore', 'pipe', 'pipe'] });
    let stderr = '';
    child.stderr.on('data', data => { stderr = (stderr + data).slice(-4096); });
    const exited = new Promise(resolve => child.once('close', (code, signal) => resolve({ code, signal })));
    const originalFetch = globalThis.fetch;
    try {
        const origin = await new Promise((resolve, reject) => {
            let output = '';
            const timer = setTimeout(() => reject(new Error('readiness timed out: ' + stderr)), 5000);
            child.once('error', error => { clearTimeout(timer); reject(error); });
            child.once('exit', code => { clearTimeout(timer); reject(new Error(`host exited ${code}: ${stderr}`)); });
            child.stdout.on('data', data => {
                output += data;
                if (output.length > 4096) { clearTimeout(timer); reject(new Error('oversized readiness')); return; }
                if (!output.includes('\n')) return;
                clearTimeout(timer);
                try {
                    const ready = JSON.parse(output.split('\n')[0]);
                    assert.match(ready.baseUrl, /^http:\/\/127\.0\.0\.1:\d+$/); resolve(ready.baseUrl);
                } catch (error) { reject(error); }
            });
        });
        const requests = [];
        globalThis.fetch = async (url, options) => {
            const response = await originalFetch(url, { ...options, signal: AbortSignal.timeout(3000) });
            requests.push({ path: new URL(url).pathname, method: options.method, body: await response.clone().json() });
            return response;
        };
        const correlationId = '10213243-5465-4768-899a-abbccddeeff0';
        const detail = { id: '00112233-4455-4677-8899-aabbccddeeff', created: '2026-10-01T12:30:00Z', status: 3 };
        const expected = { correlationId, isSuccess: true, isAuthorized: true, isValid: true, hasExceptions: false,
            validationResults: [], exceptionMessages: [], exceptionStackTrace: '', authorizationFailureReason: '' };
        const configure = artifact => { artifact.setOrigin(origin); artifact.setHttpHeadersCallback(() => ({ 'X-Correlation-ID': correlationId })); };
        const echo = new Echo(); configure(echo);
        assert.equal(echo.title, undefined);
        echo.title = ''; assert.equal((await echo.execute()).isSuccess, false); assert.equal(requests.length, 0);
        echo.title = 'production'; assert.equal(echo.hasChanges, true);
        const validation = await echo.validate(); assert.equal(validation.isSuccess, true);
        assert.deepEqual(requests[0].body, expected); assert.equal(requests[0].path, '/proxy/shop/tasks/echo/validate');
        const execution = await echo.execute();
        assert.deepEqual(requests[1].body, { ...expected, response: { title: 'production', detail } });
        assert.ok(execution.response instanceof Listing); assert.ok(execution.response.detail instanceof Detail);
        assert.ok(execution.response.detail.id instanceof Guid); assert.ok(execution.response.detail.created instanceof Date);
        assert.equal(execution.response.detail.status, Status.done); assert.equal(echo.hasChanges, false);
        const queryEnvelope = { correlationId, data: [{ title: 'snapshot', detail }], isSuccess: true, isReady: true,
            isAuthorized: true, isValid: true, hasExceptions: false, validationResults: [], exceptionMessages: [],
            exceptionStackTrace: '', paging: { page: 0, size: 0, totalItems: 0, totalPages: 0 } };
        const all = new All(); configure(all);
        const list = await all.perform(); assert.deepEqual(requests[2].body, queryEnvelope);
        assert.equal(requests[2].path, '/proxy/shop/tasks/all'); assert.equal(requests[2].method, 'GET');
        assert.ok(list.data[0] instanceof Listing); assert.ok(list.data[0].detail.id instanceof Guid);
        const find = new Find(); configure(find);
        for (const method of [QueryHttpMethod.Get, QueryHttpMethod.Query]) {
            find.setHttpMethod(method);
            const one = await find.perform({ title: 'find' });
            assert.deepEqual(requests.at(-1).body, { ...queryEnvelope, data: { title: 'find', detail } });
            assert.equal(requests.at(-1).method, method === QueryHttpMethod.Get ? 'GET' : 'QUERY');
            assert.equal(requests.at(-1).path, '/proxy/shop/tasks/find');
            assert.ok(one.data instanceof Listing); assert.ok(one.data.detail instanceof Detail);
        }
        assert.equal(requests.length, 5);
        // Independent direct server request proves portable tags are actually
        // enforced by emitted Go registration, not only a frontend validator.
        const rejected = await originalFetch(origin + '/proxy/shop/tasks/echo', { method: 'POST',
            headers: { 'Content-Type': 'application/json' }, body: '{"title":""}', signal: AbortSignal.timeout(3000) });
        const rejection = await rejected.json();
        assert.equal(rejection.isSuccess, false); assert.equal(rejection.isValid, false);
        assert.equal(rejection.validationResults[0].message, 'Title required');
    } finally {
        globalThis.fetch = originalFetch;
        child.kill('SIGTERM');
        const timer = setTimeout(() => child.kill('SIGKILL'), 3000);
        try { const exit = await exited; assert.equal(exit.code, 0, stderr); } finally { clearTimeout(timer); }
    }
});
