// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

package artifacts

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"github.com/cratis/arc.go/metadata"
)

// Header marks files owned by this generator. Output never contains timestamps.
const Header = "// Code generated by arc-gen v0.1.0-dev (format v1); DO NOT EDIT.\n"

// Filename is the sole generated output name in each selected package.
const Filename = "zz_arc_generated.go"

type dependency struct {
	typ   types.Type
	field string
}

type emitter struct {
	analysis                                                                       *analysis
	body                                                                           bytes.Buffer
	imports                                                                        map[string]string
	names                                                                          map[string]bool
	deps                                                                           []dependency
	ctx, inv, value, args, prepared, bindings, supplied, builder, err, zero, scope string
}

func emit(a *analysis) ([]byte, error) {
	e := &emitter{analysis: a, imports: map[string]string{}, names: map[string]bool{}}
	for _, name := range a.pkg.Types.Scope().Names() {
		e.names[name] = true
	}
	e.ctx = e.unique("arcCtx")
	e.inv = e.unique("arcInv")
	e.value = e.unique("arcValue")
	e.args = e.unique("arcArgs")
	e.prepared = e.unique("arcPrepared")
	e.bindings = e.unique("arcBindings")
	e.supplied = e.unique("bindings")
	e.builder = e.unique("arcBuilder")
	e.err = e.unique("arcErr")
	e.zero = e.unique("arcZero")
	e.scope = e.unique("arcScope")
	e.collectDependencies()
	e.line("// ArcBindings optionally supplies typed, stage-local dependencies without a container.")
	e.line("// Nil callbacks use execution.Resolve and declare their exact DI keys at registration.")
	e.line("// Callbacks are borrowed, may run concurrently, and must not retain the operation scope.")
	e.line("type ArcBindings struct {")
	for _, d := range e.deps {
		e.line("// %s resolves %s only when its execution stage is reached.", d.field, types.TypeString(d.typ, nil))
		e.line("%s func(%s.Context, *%s.Scope) (%s, error)", d.field, e.imp("context"), e.imp(runtimePath+"/execution"), e.typ(d.typ))
	}
	e.line("}")
	for _, d := range e.deps {
		e.line("func (%s ArcBindings) %s(%s %s.Context, %s *%s.Scope) (%s, error) {", e.bindings, "arc"+d.field, e.ctx, e.imp("context"), e.scope, e.imp(runtimePath+"/execution"), e.typ(d.typ))
		e.line("if %s.%s != nil { return %s.%s(%s, %s) }", e.bindings, d.field, e.bindings, d.field, e.ctx, e.scope)
		e.line("return %s.Resolve[%s](%s, %s)", e.imp(runtimePath+"/execution"), e.typ(d.typ), e.ctx, e.scope)
		e.line("}")
	}
	e.line("// RegisterArtifacts registers this package's artifacts through Arc's public registrars.")
	e.line("// Supply at most one binding set. Registration activates no business methods or services.")
	e.line("// Errors stop registration immediately; discard the builder after an error.")
	e.line("func RegisterArtifacts(%s *%s.Builder, %s ...ArcBindings) error {", e.builder, e.imp(runtimePath), e.supplied)
	e.line("if %s == nil || len(%s) > 1 { return %s.Errorf(\"arc-gen: expected a builder and at most one ArcBindings\") }", e.builder, e.supplied, e.imp("fmt"))
	if len(e.deps) > 0 {
		e.line("var %s ArcBindings", e.bindings)
		e.line("if len(%s) == 1 { %s = %s[0] }", e.supplied, e.bindings, e.supplied)
	}
	var derivatives []*model
	for _, models := range [][]*model{a.models, a.exports} {
		for _, model := range models {
			if model.d.targetInterface != "" {
				derivatives = append(derivatives, model)
			}
		}
	}
	if len(derivatives) > 0 {
		serialization := e.imp(runtimePath + "/serialization")
		e.line("if %s := %s.RegisterDerivedTypes(", e.err, serialization)
		for _, model := range derivatives {
			object := a.pkg.Types.Scope().Lookup(model.d.targetInterface)
			if object == nil {
				return nil, diagnostic(a.pkg, model.pos, "adapter derived interface must be declared in the owning package")
			}
			base := object.Type()
			registered := types.Type(model.typ)
			if !types.AssignableTo(registered, base) {
				registered = types.NewPointer(model.typ)
			}
			if !types.AssignableTo(registered, base) {
				return nil, diagnostic(a.pkg, model.pos, "derived model does not implement its declared interface")
			}
			e.line("%s.DerivedDeclaration{Default:%t, ID:%q, Base:%s.TypeFor[%s](), Type:%s.TypeFor[%s]()},", serialization, model.d.derivedID == "", model.d.derivedID, e.imp("reflect"), e.typ(base), e.imp("reflect"), e.typ(registered))
		}
		e.line("); %s != nil { return %s }", e.err, e.err)
	}
	for _, m := range a.models {
		e.emitModel(m)
	}
	for _, c := range a.commands {
		e.emitCommand(c)
	}
	for _, q := range a.queries {
		e.emitQuery(q)
	}
	if a.graph != nil && a.graph.verifyEndpoints {
		identities := map[string]bool{}
		for _, command := range a.commands {
			identities[command.descriptor.Declaration.Type.Identity()] = true
		}
		for _, query := range a.queries {
			identities[query.descriptor.Declaration.Identity()] = true
		}
		var endpoints []metadata.Endpoint
		for _, endpoint := range a.graph.Endpoints {
			if identities[endpoint.Identity] {
				endpoints = append(endpoints, endpoint)
			}
		}
		if len(endpoints) > 0 {
			m := e.imp(runtimePath + "/metadata")
			e.line("if %s := %s.ExpectGeneratedEndpoints(%q, []%s.Endpoint{", e.err, e.builder, a.graph.Profile.Name+":"+a.graph.Fingerprint, m)
			for _, endpoint := range endpoints {
				e.line("{Identity:%q, Method:%q, Path:%q, ValidateOnly:%t},", endpoint.Identity, endpoint.Method, endpoint.Path, endpoint.ValidateOnly)
			}
			e.line("}); %s != nil { return %s }", e.err, e.err)
		}
	}
	e.line("return nil\n}")
	var out bytes.Buffer
	out.WriteString(Header)
	out.WriteString("// Copyright (c) Cratis. All rights reserved.\n// Licensed under the MIT license. See LICENSE file in the project root for full license information.\n\n")
	fmt.Fprintf(&out, "package %s\n\nimport (\n", a.pkg.Name)
	paths := make([]string, 0, len(e.imports))
	for path := range e.imports {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, path := range paths {
		fmt.Fprintf(&out, "%s %q\n", e.imports[path], path)
	}
	out.WriteString(")\n\n")
	out.Write(e.body.Bytes())
	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated %s: %w", a.pkg.PkgPath, err)
	}
	return formatted, nil
}

func (e *emitter) unique(base string) string {
	name := base
	for i := 2; e.names[name]; i++ {
		name = base + strconv.Itoa(i)
	}
	e.names[name] = true
	return name
}
func (e *emitter) imp(path string) string {
	if name, ok := e.imports[path]; ok {
		return name
	}
	base := path[strings.LastIndex(path, "/")+1:]
	if path == runtimePath {
		base = "arc"
	}
	name := e.unique("arcgen" + strings.ReplaceAll(base, ".", ""))
	e.imports[path] = name
	return name
}
func (e *emitter) typ(t types.Type) string {
	return types.TypeString(t, func(pkg *types.Package) string {
		if pkg == e.analysis.pkg.Types {
			return ""
		}
		return e.imp(pkg.Path())
	})
}
func (e *emitter) line(format string, args ...any) { fmt.Fprintf(&e.body, format+"\n", args...) }
func (e *emitter) collectDependencies() {
	all := map[string]types.Type{}
	collect := func(m method) {
		for _, p := range m.params {
			if p.kind == "dependency" {
				all[types.TypeString(p.typ, nil)] = p.typ
			}
		}
	}
	for _, c := range e.analysis.commands {
		collect(c.handle)
		if c.provide != nil {
			collect(*c.provide)
		}
	}
	for _, q := range e.analysis.queries {
		collect(q.call)
	}
	keys := make([]string, 0, len(all))
	for key := range all {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	fields := map[string]bool{}
	for _, key := range keys {
		t := all[key]
		base := t
		if p, ok := types.Unalias(base).(*types.Pointer); ok {
			base = p.Elem()
		}
		name := "Dependency"
		if n, ok := types.Unalias(base).(*types.Named); ok {
			name = n.Obj().Name()
		}
		runes := []rune(name)
		runes[0] = unicode.ToUpper(runes[0])
		name = "Resolve" + string(runes)
		field := name
		for n := 2; fields[field]; n++ {
			field = name + strconv.Itoa(n)
		}
		fields[field] = true
		e.deps = append(e.deps, dependency{typ: t, field: field})
	}
}
func (e *emitter) dep(t types.Type) dependency {
	for _, d := range e.deps {
		if types.Identical(t, d.typ) {
			return d
		}
	}
	panic("missing analyzed dependency")
}
func (e *emitter) auth(a *metadata.Authorization) string {
	if a == nil {
		return "nil"
	}
	m := e.imp(runtimePath + "/metadata")
	var text strings.Builder
	fmt.Fprintf(&text, "&%s.Authorization{AllowAnonymous:%t,", m, a.AllowAnonymous)
	if len(a.Requirements) > 0 {
		fmt.Fprintf(&text, "Requirements:[]%s.AuthorizationRequirement{", m)
		for _, r := range a.Requirements {
			fmt.Fprintf(&text, "{Policy:%q,", r.Policy)
			if len(r.Roles) > 0 {
				text.WriteString("Roles:[]string{")
				for _, role := range r.Roles {
					fmt.Fprintf(&text, "%q,", role)
				}
				text.WriteString("},")
			}
			text.WriteString("},")
		}
		text.WriteString("},")
	}
	text.WriteString("}")
	return text.String()
}
func (e *emitter) emitModel(m *model) {
	q := e.imp(runtimePath + "/queries")
	e.line("if %s := %s.RegisterReadModel[%s](%s, %s.WithModelName(%q), %s.WithModelPath(%q),", e.err, q, e.typ(m.typ), e.builder, q, m.d.name, q, m.d.path)
	if e.analysis.namespace != "" || e.analysis.staticNamespace {
		e.line("%s.WithModelNamespace(%q),", q, e.analysis.namespace)
	}
	if m.d.exclude {
		e.line("%s.WithModelExcludeFromDiscovery(true),", q)
	}
	if m.d.auth != nil {
		e.line("%s.WithModelAuthorization(%s),", q, strings.TrimPrefix(e.auth(m.d.auth), "&"))
	}
	e.line("); %s != nil { return %s }", e.err, e.err)
}
func (e *emitter) manifest(m method) string {
	var deps []dependency
	seen := map[string]bool{}
	for _, p := range m.params {
		if p.kind == "dependency" {
			d := e.dep(p.typ)
			if !seen[d.field] {
				deps = append(deps, d)
				seen[d.field] = true
			}
		}
	}
	if len(deps) == 0 {
		return ""
	}
	name := e.unique("arcKeys")
	di := e.imp("github.com/cratis/fundamentals.go/dependencyinjection")
	e.line("var %s []%s.Key", name, di)
	for _, d := range deps {
		e.line("if %s.%s == nil { %s = append(%s, %s.KeyFor[%s]()) }", e.bindings, d.field, name, name, di, e.typ(d.typ))
	}
	return name
}
func (e *emitter) emitCommand(c command) {
	if c.descriptor != nil {
		declaration := c.descriptor.Declaration
		c.d.name, c.d.path, c.d.auth, c.d.exclude, c.d.severity = declaration.Type.Name, declaration.Path, declaration.Authorization, declaration.ExcludeFromDiscovery, declaration.BlockOnValidationSeverity
	}
	cmd := e.imp(runtimePath + "/commands")
	validator := ""
	if e.analysis.graph != nil && e.analysis.graph.verifyEndpoints && c.descriptor.PortableRules {
		validator = e.unique("arcValidator")
		e.line("%s, %s := %s.NewPortable[%s]()", validator, e.err, e.imp(runtimePath+"/validation"), e.typ(c.receiver))
		e.line("if %s != nil { return %s }", e.err, e.err)
	}
	context := e.imp("context")
	ct := e.typ(c.receiver)
	hkeys := e.manifest(c.handle)
	pkeys := ""
	if c.provide != nil {
		pkeys = e.manifest(*c.provide)
	}
	out := cmd + ".NoResponse"
	if c.handle.output != nil {
		out = e.typ(c.handle.output)
	}
	e.line("if %s := %s.Register[%s](%s,", e.err, cmd, ct, e.builder)
	if c.provide == nil {
		e.line("%s.Invoke(func(%s %s.Context, %s *%s.Invocation, %s %s) (%s, error) {", cmd, e.ctx, context, e.inv, cmd, e.value, ct, out)
		e.emitCall(c.handle, e.value+".Handle", out, false, "")
		e.line("}),")
	} else {
		pt := "struct{}"
		if c.payload != nil {
			pt = e.typ(c.payload)
		}
		prep := cmd + ".Preparation[" + pt + "]"
		e.line("%s.Prepare(func(%s %s.Context, %s *%s.Invocation, %s %s) (%s, error) {", cmd, e.ctx, context, e.inv, cmd, e.value, ct, prep)
		e.emitCall(*c.provide, e.value+".Provide", prep, true, c.control)
		e.line("}, func(%s %s.Context, %s *%s.Invocation, %s %s, %s %s) (%s, error) {", e.ctx, context, e.inv, cmd, e.value, ct, e.prepared, pt, out)
		e.emitCall(c.handle, e.value+".Handle", out, false, "")
		e.line("}),")
	}
	e.line("%s.WithName[%s](%q), %s.WithPath[%s](%q),", cmd, ct, c.d.name, cmd, ct, c.d.path)
	if e.analysis.namespace != "" || e.analysis.staticNamespace {
		e.line("%s.WithNamespace[%s](%q),", cmd, ct, e.analysis.namespace)
	}
	if c.d.auth != nil {
		e.line("%s.WithAuthorization[%s](%s),", cmd, ct, strings.TrimPrefix(e.auth(c.d.auth), "&"))
	}
	if c.d.exclude {
		e.line("%s.WithExcludeFromDiscovery[%s](true),", cmd, ct)
	}
	response := c.d.response
	if e.analysis.graph != nil {
		if override, exists := e.analysis.graph.Profile.Responses[(metadata.TypeName{Namespace: e.analysis.namespace, Name: c.d.name}).Identity()]; exists {
			response = override
		}
	}
	if e.analysis.graph != nil && e.analysis.graph.verifyEndpoints {
		response = c.descriptor.ResponseKind
	}
	if validator != "" {
		e.line("%s.WithValidator[%s](%s),", cmd, ct, validator)
	}
	switch response {
	case "none":
		e.line("%s.WithNoResponse[%s](),", cmd, ct)
	case "value":
		if c.handle.output == nil {
			return
		}
		responseType := c.handle.output
		if namedType(responseType, runtimePath+"/commands", "Outcome") {
			responseType = types.Unalias(responseType).(*types.Named).TypeArgs().At(0)
		}
		e.line("%s.WithResponseType[%s, %s](),", cmd, ct, e.typ(responseType))
	}
	if c.d.severity != nil {
		e.line("%s.WithBlockOnValidationSeverity[%s](%s.Severity(%d)),", cmd, ct, e.imp(runtimePath+"/validation"), *c.d.severity)
	}
	if hkeys != "" {
		e.line("%s.WithHandlingDependencies[%s](%s...),", cmd, ct, hkeys)
	}
	if pkeys != "" {
		e.line("%s.WithPreparationDependencies[%s](%s...),", cmd, ct, pkeys)
	}
	e.line("); %s != nil { return %s }", e.err, e.err)
}
func (e *emitter) emitQuery(q query) {
	if q.descriptor != nil {
		declaration := q.descriptor.Declaration
		q.d.name, q.d.auth, q.d.http = declaration.Name, declaration.Authorization, string(declaration.HTTPMethod)
	}
	queries := e.imp(runtimePath + "/queries")
	args := queries + ".NoArguments"
	if q.args != nil {
		args = e.typ(q.args)
	}
	keys := e.manifest(q.call)
	e.line("if %s := %s.Register[%s](%s, %q, %s.Invoke(func(%s %s.Context, %s *%s.Invocation, %s %s) (%s, error) {", e.err, queries, e.typ(q.model.typ), e.builder, q.d.name, queries, e.ctx, e.imp("context"), e.inv, queries, e.args, args, e.typ(q.call.output))
	call := q.call.decl.Name.Name
	if q.call.decl.Recv != nil {
		call = "(" + e.typ(q.model.typ) + "{})." + call
	}
	e.emitCall(q.call, call, e.typ(q.call.output), false, "")
	e.line("}),")
	if q.d.auth != nil {
		e.line("%s.WithAuthorization[%s](%s),", queries, args, strings.TrimPrefix(e.auth(q.d.auth), "&"))
	}
	if q.d.http != "" {
		e.line("%s.WithHTTPMethod[%s](%q),", queries, args, q.d.http)
	}
	if q.d.exclude {
		e.line("%s.WithExcludeFromDiscovery[%s](true),", queries, args)
	}
	if q.d.hasPath {
		e.line("%s.WithPath[%s](%q),", queries, args, q.d.path)
	}
	if keys != "" {
		e.line("%s.WithDependencies[%s](%s...),", queries, args, keys)
	}
	e.line("); %s != nil { return %s }", e.err, e.err)
}
func (e *emitter) emitCall(m method, call, out string, provide bool, control string) {
	var args []string
	for _, p := range m.params {
		var value string
		switch p.kind {
		case "context":
			value = e.ctx
		case "commandContext":
			value = e.inv + ".CommandContext()"
		case "queryContext":
			value = e.inv + ".QueryContext()"
		case "parameters":
			value = e.inv + ".QueryContext().Parameters()"
		case "arguments":
			value = e.args
		case "provided":
			value = e.prepared
		default:
			value = e.unique("arcDependency")
			e.line("%s, %s := %s.arc%s(%s, %s.Scope())", value, e.err, e.bindings, e.dep(p.typ).field, e.ctx, e.inv)
			e.line("if %s != nil { var %s %s; return %s, %s }", e.err, e.zero, out, e.zero, e.err)
		}
		args = append(args, value)
	}
	invocation := call + "(" + strings.Join(args, ", ") + ")"
	cmd := ""
	if provide || m.output == nil {
		cmd = e.imp(runtimePath + "/commands")
	}
	if m.output == nil {
		e.line("return %s.NoResponse{}, %s", cmd, invocation)
		return
	}
	if !provide || control == "preparation" {
		e.line("return %s", invocation)
		return
	}
	v := e.unique("arcProvided")
	e.line("%s, %s := %s", v, e.err, invocation)
	e.line("if %s != nil { var %s %s; return %s, %s }", e.err, e.zero, out, e.zero, e.err)
	id := e.inv + ".CommandContext().CorrelationID()"
	switch control {
	case "":
		e.line("return %s.Provided(%s), nil", cmd, v)
	case "validation":
		e.line("return %s.ProvidedWith(struct{}{}, %s.WithValidationResults(%s, %s)), nil", cmd, cmd, id, v)
	case "validations":
		e.line("return %s.ProvidedWith(struct{}{}, %s.WithValidationResults(%s, %s...)), nil", cmd, cmd, id, v)
	case "result":
		e.line("return %s.ProvidedWith(struct{}{}, %s), nil", cmd, v)
	case "authorization":
		e.line("if !%s.IsAllowed() { return %s.StopProviding[struct{}](%s.Unauthorized(%s, %s.Reason())), nil }", v, cmd, cmd, id, v)
		e.line("return %s.Provided(struct{}{}), nil", cmd)
	}
}
