// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

package artifacts

import (
	"bytes"
	"context"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func bindingsConfig(t *testing.T, dir string, cfg serviceBindingsConfig) string {
	t.Helper()
	cfg.FormatVersion = 1
	if cfg.Package == "" {
		cfg.Package = "example.test/consumer"
	}
	data, err := json.Marshal(cfg)
	if err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(dir, "bindings.json")
	put(t, path, string(data))
	return path
}
func TestServiceOnlyPublicationDeterminismStaleCleanupAndForeignOwnership(t *testing.T) {
	dir := consumer(t)
	put(t, filepath.Join(dir, "input.go"), "package consumer\ntype Foo struct{}\nfunc NewFoo() *Foo { return &Foo{} }\n")
	foreign := filepath.Join(dir, "unselected", Filename)
	foreignBytes := Header + "package unselected\nconst Keep = true\n"
	put(t, foreign, foreignBytes)
	config := Config{Dir: dir, BindingsConfigFile: bindingsConfig(t, dir, serviceBindingsConfig{})}
	generate(t, config)
	first := get(t, filepath.Join(dir, Filename))
	if !bytes.Contains(first, []byte("RegisterServices")) || !bytes.Contains(first, []byte("NewFoo()")) {
		t.Fatal("empty service-only output")
	}
	generate(t, config)
	if !bytes.Equal(first, get(t, filepath.Join(dir, Filename))) {
		t.Fatal("service bytes changed")
	}
	config.Check = true
	generate(t, config)
	if string(get(t, foreign)) != foreignBytes {
		t.Fatal("unselected output changed")
	}
	// Removing the opt-in deletes selected stale owned services, not foreign files.
	generate(t, Config{Dir: dir})
	if _, err := os.Stat(filepath.Join(dir, Filename)); !os.IsNotExist(err) {
		t.Fatal(err)
	}
	put(t, filepath.Join(dir, Filename), "// Code generated by another-generator; DO NOT EDIT.\npackage consumer\n")
	before := get(t, filepath.Join(dir, Filename))
	config.Check = false
	if err := Generate(t.Context(), config); err == nil {
		t.Fatal("adopted foreign owner")
	}
	if !bytes.Equal(before, get(t, filepath.Join(dir, Filename))) {
		t.Fatal("foreign output changed")
	}
}
func TestInvalidServicesLeaveEverySelectedOutputUnchanged(t *testing.T) {
	dir := consumer(t)
	put(t, filepath.Join(dir, "input.go"), "package consumer\ntype Foo struct{}\nfunc NewFoo() *Foo { return &Foo{} }\n")
	put(t, filepath.Join(dir, "other", "input.go"), "package other\n//arc:command\ntype Add struct{}\nfunc (Add) Handle() error{return nil}\n")
	config := Config{Dir: dir, Patterns: []string{".", "./other"}, BindingsConfigFile: bindingsConfig(t, dir, serviceBindingsConfig{})}
	generate(t, config)
	put(t, filepath.Join(dir, "input.go"), "package consumer\ntype Foo struct{}\nfunc NewFoo(int) *Foo { return &Foo{} }\n")
	before := outputInventory(t, dir)
	if err := Generate(t.Context(), config); err == nil || !strings.Contains(err.Error(), "BT012") {
		t.Fatal(err)
	}
	assertOutputInventory(t, dir, before)
}
func TestServicesDoNotFlattenIntoArcStageManifestAndRejectDTOConstruction(t *testing.T) {
	dir := consumer(t)
	put(t, filepath.Join(dir, "input.go"), `package consumer
 type Dep struct{}
 type Foo struct{}
 func NewFoo(*Dep) *Foo{return &Foo{}}
 //arc:command
 //arc:allow-anonymous
 type Add struct{}
 func (Add) Handle(*Foo) error{return nil}
 `)
	config := Config{Dir: dir, BindingsConfigFile: bindingsConfig(t, dir, serviceBindingsConfig{})}
	generate(t, config)
	data := get(t, filepath.Join(dir, Filename))
	// Dep is a constructor edge, not a callback or command stage key.
	if bytes.Contains(data, []byte("ResolveDep")) || bytes.Count(data, []byte("KeyFor[*Dep]")) != 0 || !bytes.Contains(data, []byte("BindFunc1")) {
		t.Fatal(string(data))
	}
	before := data
	put(t, filepath.Join(dir, "ctor.go"), "package consumer\nfunc NewAdd() Add{return Add{}}\n")
	if err := Generate(t.Context(), config); err == nil || !strings.Contains(err.Error(), "command DTO") {
		t.Fatal(err)
	}
	if !bytes.Equal(before, get(t, filepath.Join(dir, Filename))) {
		t.Fatal("invalid DTO construction wrote output")
	}
}
func TestServicesPreserveMixedOutputOwnershipCollisions(t *testing.T) {
	dir := consumer(t)
	put(t, filepath.Join(dir, "input.go"), "package consumer\ntype Foo struct{}\nfunc NewFoo() Foo{return Foo{}}\n")
	config := Config{Dir: dir, BindingsConfigFile: bindingsConfig(t, dir, serviceBindingsConfig{})}
	generate(t, config)
	before := get(t, filepath.Join(dir, Filename))
	config.TypeScriptOut = "web"
	if err := Generate(t.Context(), config); err == nil || !strings.Contains(err.Error(), "no manifest ownership") {
		t.Fatal(err)
	}
	if !bytes.Equal(before, get(t, filepath.Join(dir, Filename))) {
		t.Fatal("mixed ownership changed output")
	}
}

func runServiceCLI(t *testing.T, dir, config, pattern string) []byte {
	t.Helper()
	ctx, cancel := context.WithTimeout(t.Context(), 45*time.Second)
	defer cancel()
	command := exec.CommandContext(ctx, "go", "run", "./cmd/arc-gen", "-dir", dir, "-bindings-config", config, pattern)
	command.Dir = "../.."
	command.Env = append(os.Environ(), "GOWORK=off", "GOTOOLCHAIN=local", "ARC_BINDINGS_GENERATION=trap")
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("production service CLI: %v\n%s", err, output)
	}
	return output
}

func TestProductionCLIServiceBindingsForeignGeneratorOwnership(t *testing.T) {
	dir := consumer(t)
	fixture := filepath.Join("testdata", "servicebindings")
	put(t, filepath.Join(dir, "input.go"), string(get(t, filepath.Join(fixture, "input.go.txt"))))
	put(t, filepath.Join(dir, "foreign.go"), string(get(t, filepath.Join(fixture, "foreign.go.txt"))))
	cfg, err := readServiceBindingsConfig(filepath.Join(fixture, "bindings.json"))
	if err != nil {
		t.Fatal(err)
	}
	cfg.Duplicates = "keepExisting"
	cfg.Existing = append(cfg.Existing, serviceExistingConfig{Key: "*Foo", Lifetime: "singleton"})
	output := runServiceCLI(t, dir, bindingsConfig(t, dir, *cfg), ".")
	data := get(t, filepath.Join(dir, Filename))
	if bytes.Contains(data, []byte("NewFoo()")) || !bytes.Contains(output, []byte("BT013 information")) || !bytes.Contains(output, []byte("1 explicitly retained")) {
		t.Fatal("foreign ownership not retained", string(output))
	}
	put(t, filepath.Join(dir, "foreign_test.go"), string(get(t, filepath.Join(fixture, "foreign_test.go.txt"))))
	ctx, cancel := context.WithTimeout(t.Context(), 45*time.Second)
	defer cancel()
	command := exec.CommandContext(ctx, "go", "test", "-mod=mod", "-count=1", "-timeout=30s", "./...")
	command.Dir = dir
	command.Env = append(os.Environ(), "GOWORK=off", "GOTOOLCHAIN=local")
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("foreign-owner compiled witness: %v\n%s", err, output)
	}
}

func TestProductionCLIServiceBindingsExternalCompiledWitness(t *testing.T) {
	dir := consumer(t)
	fixture := filepath.Join("testdata", "servicebindings")
	source := get(t, filepath.Join(fixture, "input.go.txt"))
	if bytes.Contains(source, []byte("func RegisterServices")) {
		t.Fatal("handwritten renderer witness")
	}
	put(t, filepath.Join(dir, "input.go"), string(source))
	put(t, filepath.Join(dir, "bindings.json"), string(get(t, filepath.Join(fixture, "bindings.json"))))
	cli := func(extra ...string) []byte {
		t.Helper()
		ctx, cancel := context.WithTimeout(t.Context(), 45*time.Second)
		defer cancel()
		args := []string{"run", "./cmd/arc-gen", "-dir", dir, "-bindings-config", filepath.Join(dir, "bindings.json")}
		args = append(args, extra...)
		args = append(args, ".")
		command := exec.CommandContext(ctx, "go", args...)
		command.Dir = "../.."
		command.Env = append(os.Environ(), "GOWORK=off", "GOTOOLCHAIN=local", "ARC_BINDINGS_GENERATION=trap")
		output, err := command.CombinedOutput()
		if err != nil {
			t.Fatalf("production CLI: %v\n%s", err, output)
		}
		return output
	}
	inventory := cli()
	if !bytes.Contains(inventory, []byte("service bindings published")) || bytes.Contains(inventory, []byte("0 service bindings")) {
		t.Fatal(string(inventory))
	}
	first := get(t, filepath.Join(dir, Filename))
	cli()
	if !bytes.Equal(first, get(t, filepath.Join(dir, Filename))) {
		t.Fatal("production bytes differ")
	}
	cli("-check")
	for _, name := range []string{"BindFunc1", "BindFunc2", "BindFunc3", "BindFunc4", "BindBorrowed", "NewWide("} {
		if !bytes.Contains(first, []byte(name)) {
			t.Fatalf("missing production inventory %s", name)
		}
	}
	if bytes.Contains(first, []byte("BindFunc0")) {
		t.Fatal("nonexistent adapter")
	}
	// Inspect actual resolved modules, not merely the fixture's requested manifest.
	ctx, cancel := context.WithTimeout(t.Context(), 45*time.Second)
	defer cancel()
	command := exec.CommandContext(ctx, "go", "list", "-m", "-json", "all")
	command.Dir = dir
	command.Env = append(os.Environ(), "GOWORK=off", "GOTOOLCHAIN=local")
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("resolved module pins: %v\n%s", err, output)
	}
	decoder := json.NewDecoder(bytes.NewReader(output))
	found := map[string]bool{}
	pins := map[string]string{runtimePath: "v0.0.0-20261003142617-78ebbf8fdff8", "github.com/cratis/fundamentals.go": "v0.2.0"}
	checkout, err := filepath.Abs("../../..")
	if err != nil {
		t.Fatal(err)
	}
	for decoder.More() {
		var module struct {
			Path, Version, Dir string
			Replace            *json.RawMessage
		}
		if err := decoder.Decode(&module); err != nil {
			t.Fatal(err)
		}
		if module.Replace != nil {
			t.Fatalf("replacement source: %+v", module)
		}
		if pin, ok := pins[module.Path]; ok {
			if module.Version != pin || module.Dir == "" || strings.HasPrefix(module.Dir, checkout+string(os.PathSeparator)) {
				t.Fatalf("unqualified pin/source: %+v", module)
			}
			found[module.Path] = true
		}
	}
	if len(found) != len(pins) {
		t.Fatal("pins not resolved", found)
	}
	put(t, filepath.Join(dir, "graphs", "input.go"), string(get(t, filepath.Join(fixture, "graphs.go.txt"))))
	graphConfig := bindingsConfig(t, dir, serviceBindingsConfig{Package: "example.test/consumer/graphs"})
	runServiceCLI(t, dir, graphConfig, "./graphs")
	put(t, filepath.Join(dir, "graphs_test.go"), string(get(t, filepath.Join(fixture, "graphs_test.go.txt"))))
	put(t, filepath.Join(dir, "contract_test.go"), string(get(t, filepath.Join(fixture, "contract_test.go.txt"))))
	ctxRun, cancelRun := context.WithTimeout(t.Context(), 45*time.Second)
	defer cancelRun()
	command = exec.CommandContext(ctxRun, "go", "test", "-mod=mod", "-count=1", "-timeout=30s", "./...")
	command.Dir = dir
	command.Env = append(os.Environ(), "GOWORK=off", "GOTOOLCHAIN=local")
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("external generated service/runtime witness: %v\n%s", err, output)
	}
}
