// Code generated by an analyzer fixture; DO NOT EDIT.

package queries

// These names must not prevent diagnostics after arc-gen has generated adapters.
func RegisterArtifacts() {}

type ArcBindings struct{}

//arc:query model=View
func Generated(args Arguments) (View, error) {
	_ = ConceptAlias(args.Name)
	panic("generated query executed")
}
