// Code generated by a fixture. DO NOT EDIT.

package declarations

//arc:query model=Model
func GeneratedWrong() (Wrong, error) { return Wrong{}, nil }

type GeneratedMissingMarker struct{ Name string }

func (GeneratedMissingMarker) Handle() error { return nil }

type GeneratedExternal struct{}

func (GeneratedExternal) Handle(CommandAlias) error { return nil }

//arc:command
type GeneratedMissingHandle struct{}

//arc:command
type GeneratedPreparation struct{}

func (GeneratedPreparation) Handle() error            { return nil }
func (GeneratedPreparation) Provide() (string, error) { return "", nil }

//arc:command
type GeneratedInjected struct{}

func (GeneratedInjected) Handle(Model) error { return nil }

//arc:query model=Model
func GeneratedGeneric[T any]() (Model, error) { return Model{}, nil }

//arc:query model=Model
//arc:authorize
//arc:allow-anonymous
func GeneratedConflict() (Model, error) { return Model{}, nil }
