// Code generated by arc-gen v0.1.0-dev (format v1); DO NOT EDIT.
// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

package generatedconsumer

import (
	arcgencontext "context"
	arcgenfmt "fmt"
	arcgenarc "github.com/cratis/arc.go"
	arcgencommands "github.com/cratis/arc.go/commands"
	arcgenexecution "github.com/cratis/arc.go/execution"
	arcgenmetadata "github.com/cratis/arc.go/metadata"
	arcgenqueries "github.com/cratis/arc.go/queries"
	arcgenvalidation "github.com/cratis/arc.go/validation"
	arcgendependencyinjection "github.com/cratis/fundamentals.go/dependencyinjection"
)

// ArcBindings optionally supplies typed, stage-local dependencies without a container.
// Nil callbacks use execution.Resolve and declare their exact DI keys at registration.
// Callbacks are borrowed, may run concurrently, and must not retain the operation scope.
type ArcBindings struct {
	// ResolveItemQueries resolves github.com/cratis/arc.go/ContractTests/internal/generatedconsumer.ItemQueries only when its execution stage is reached.
	ResolveItemQueries func(arcgencontext.Context, *arcgenexecution.Scope) (ItemQueries, error)
	// ResolveReader resolves github.com/cratis/arc.go/ContractTests/internal/generatedconsumer.Reader only when its execution stage is reached.
	ResolveReader func(arcgencontext.Context, *arcgenexecution.Scope) (Reader, error)
	// ResolveWriter resolves github.com/cratis/arc.go/ContractTests/internal/generatedconsumer.Writer only when its execution stage is reached.
	ResolveWriter func(arcgencontext.Context, *arcgenexecution.Scope) (Writer, error)
}

func (arcBindings ArcBindings) arcResolveItemQueries(arcCtx arcgencontext.Context, arcScope *arcgenexecution.Scope) (ItemQueries, error) {
	if arcBindings.ResolveItemQueries != nil {
		return arcBindings.ResolveItemQueries(arcCtx, arcScope)
	}
	return arcgenexecution.Resolve[ItemQueries](arcCtx, arcScope)
}
func (arcBindings ArcBindings) arcResolveReader(arcCtx arcgencontext.Context, arcScope *arcgenexecution.Scope) (Reader, error) {
	if arcBindings.ResolveReader != nil {
		return arcBindings.ResolveReader(arcCtx, arcScope)
	}
	return arcgenexecution.Resolve[Reader](arcCtx, arcScope)
}
func (arcBindings ArcBindings) arcResolveWriter(arcCtx arcgencontext.Context, arcScope *arcgenexecution.Scope) (Writer, error) {
	if arcBindings.ResolveWriter != nil {
		return arcBindings.ResolveWriter(arcCtx, arcScope)
	}
	return arcgenexecution.Resolve[Writer](arcCtx, arcScope)
}

// RegisterArtifacts registers this package's artifacts through Arc's public registrars.
// Supply at most one binding set. Registration activates no business methods or services.
// Errors stop registration immediately; discard the builder after an error.
func RegisterArtifacts(arcBuilder *arcgenarc.Builder, bindings ...ArcBindings) error {
	if arcBuilder == nil || len(bindings) > 1 {
		return arcgenfmt.Errorf("arc-gen: expected a builder and at most one ArcBindings")
	}
	var arcBindings ArcBindings
	if len(bindings) == 1 {
		arcBindings = bindings[0]
	}
	if arcErr := arcgenqueries.RegisterReadModel[Item](arcBuilder, arcgenqueries.WithModelName("Item"), arcgenqueries.WithModelPath(""),
		arcgenqueries.WithModelNamespace("Generated.Shop"),
		arcgenqueries.WithModelAuthorization(arcgenmetadata.Authorization{AllowAnonymous: false, Requirements: []arcgenmetadata.AuthorizationRequirement{{Policy: "", Roles: []string{"Reader"}}}}),
	); arcErr != nil {
		return arcErr
	}
	var arcKeys []arcgendependencyinjection.Key
	if arcBindings.ResolveWriter == nil {
		arcKeys = append(arcKeys, arcgendependencyinjection.KeyFor[Writer]())
	}
	var arcKeys2 []arcgendependencyinjection.Key
	if arcBindings.ResolveReader == nil {
		arcKeys2 = append(arcKeys2, arcgendependencyinjection.KeyFor[Reader]())
	}
	if arcErr := arcgencommands.Register[AddItem](arcBuilder,
		arcgencommands.Prepare(func(arcCtx arcgencontext.Context, arcInv *arcgencommands.Invocation, arcValue AddItem) (arcgencommands.Preparation[State], error) {
			arcDependency, arcErr := arcBindings.arcResolveReader(arcCtx, arcInv.Scope())
			if arcErr != nil {
				var arcZero arcgencommands.Preparation[State]
				return arcZero, arcErr
			}
			return arcValue.Provide(arcCtx, arcDependency, arcInv.CommandContext())
		}, func(arcCtx arcgencontext.Context, arcInv *arcgencommands.Invocation, arcValue AddItem, arcPrepared State) (string, error) {
			arcDependency2, arcErr := arcBindings.arcResolveWriter(arcCtx, arcInv.Scope())
			if arcErr != nil {
				var arcZero string
				return arcZero, arcErr
			}
			return arcValue.Handle(arcCtx, arcPrepared, arcDependency2)
		}),
		arcgencommands.WithName[AddItem]("AddItem"), arcgencommands.WithPath[AddItem](""),
		arcgencommands.WithNamespace[AddItem]("Generated.Shop"),
		arcgencommands.WithAuthorization[AddItem](arcgenmetadata.Authorization{AllowAnonymous: false, Requirements: []arcgenmetadata.AuthorizationRequirement{{Policy: "", Roles: []string{"Editor", "Admin"}}, {Policy: "", Roles: []string{"Verified"}}}}),
		arcgencommands.WithExcludeFromDiscovery[AddItem](true),
		arcgencommands.WithBlockOnValidationSeverity[AddItem](arcgenvalidation.Severity(2)),
		arcgencommands.WithHandlingDependencies[AddItem](arcKeys...),
		arcgencommands.WithPreparationDependencies[AddItem](arcKeys2...),
	); arcErr != nil {
		return arcErr
	}
	var arcKeys3 []arcgendependencyinjection.Key
	if arcBindings.ResolveWriter == nil {
		arcKeys3 = append(arcKeys3, arcgendependencyinjection.KeyFor[Writer]())
	}
	if arcErr := arcgencommands.Register[Checked](arcBuilder,
		arcgencommands.Prepare(func(arcCtx arcgencontext.Context, arcInv *arcgencommands.Invocation, arcValue Checked) (arcgencommands.Preparation[struct{}], error) {
			arcProvided, arcErr := arcValue.Provide()
			if arcErr != nil {
				var arcZero arcgencommands.Preparation[struct{}]
				return arcZero, arcErr
			}
			return arcgencommands.ProvidedWith(struct{}{}, arcgencommands.WithValidationResults(arcInv.CommandContext().CorrelationID(), arcProvided...)), nil
		}, func(arcCtx arcgencontext.Context, arcInv *arcgencommands.Invocation, arcValue Checked, arcPrepared struct{}) (string, error) {
			arcDependency3, arcErr := arcBindings.arcResolveWriter(arcCtx, arcInv.Scope())
			if arcErr != nil {
				var arcZero string
				return arcZero, arcErr
			}
			return arcValue.Handle(arcCtx, arcDependency3)
		}),
		arcgencommands.WithName[Checked]("Checked"), arcgencommands.WithPath[Checked](""),
		arcgencommands.WithNamespace[Checked]("Generated.Shop"),
		arcgencommands.WithAuthorization[Checked](arcgenmetadata.Authorization{AllowAnonymous: true}),
		arcgencommands.WithHandlingDependencies[Checked](arcKeys3...),
	); arcErr != nil {
		return arcErr
	}
	var arcKeys4 []arcgendependencyinjection.Key
	if arcBindings.ResolveWriter == nil {
		arcKeys4 = append(arcKeys4, arcgendependencyinjection.KeyFor[Writer]())
	}
	if arcErr := arcgencommands.Register[Guarded](arcBuilder,
		arcgencommands.Prepare(func(arcCtx arcgencontext.Context, arcInv *arcgencommands.Invocation, arcValue Guarded) (arcgencommands.Preparation[struct{}], error) {
			arcProvided2, arcErr := arcValue.Provide(arcCtx)
			if arcErr != nil {
				var arcZero arcgencommands.Preparation[struct{}]
				return arcZero, arcErr
			}
			if !arcProvided2.IsAllowed() {
				return arcgencommands.StopProviding[struct{}](arcgencommands.Unauthorized(arcInv.CommandContext().CorrelationID(), arcProvided2.Reason())), nil
			}
			return arcgencommands.Provided(struct{}{}), nil
		}, func(arcCtx arcgencontext.Context, arcInv *arcgencommands.Invocation, arcValue Guarded, arcPrepared struct{}) (string, error) {
			arcDependency4, arcErr := arcBindings.arcResolveWriter(arcCtx, arcInv.Scope())
			if arcErr != nil {
				var arcZero string
				return arcZero, arcErr
			}
			return arcValue.Handle(arcCtx, arcDependency4)
		}),
		arcgencommands.WithName[Guarded]("Guarded"), arcgencommands.WithPath[Guarded](""),
		arcgencommands.WithNamespace[Guarded]("Generated.Shop"),
		arcgencommands.WithAuthorization[Guarded](arcgenmetadata.Authorization{AllowAnonymous: true}),
		arcgencommands.WithHandlingDependencies[Guarded](arcKeys4...),
	); arcErr != nil {
		return arcErr
	}
	if arcErr := arcgencommands.Register[Rename](arcBuilder,
		arcgencommands.Prepare(func(arcCtx arcgencontext.Context, arcInv *arcgencommands.Invocation, arcValue Rename) (arcgencommands.Preparation[State], error) {
			arcProvided3, arcErr := arcValue.Provide(arcCtx)
			if arcErr != nil {
				var arcZero arcgencommands.Preparation[State]
				return arcZero, arcErr
			}
			return arcgencommands.Provided(arcProvided3), nil
		}, func(arcCtx arcgencontext.Context, arcInv *arcgencommands.Invocation, arcValue Rename, arcPrepared State) (string, error) {
			return arcValue.Handle(arcCtx, arcPrepared)
		}),
		arcgencommands.WithName[Rename]("Rename"), arcgencommands.WithPath[Rename](""),
		arcgencommands.WithNamespace[Rename]("Generated.Shop"),
		arcgencommands.WithAuthorization[Rename](arcgenmetadata.Authorization{AllowAnonymous: true}),
	); arcErr != nil {
		return arcErr
	}
	if arcErr := arcgencommands.Register[*Reset](arcBuilder,
		arcgencommands.Invoke(func(arcCtx arcgencontext.Context, arcInv *arcgencommands.Invocation, arcValue *Reset) (arcgencommands.NoResponse, error) {
			return arcgencommands.NoResponse{}, arcValue.Handle()
		}),
		arcgencommands.WithName[*Reset]("Reset"), arcgencommands.WithPath[*Reset](""),
		arcgencommands.WithNamespace[*Reset]("Generated.Shop"),
		arcgencommands.WithAuthorization[*Reset](arcgenmetadata.Authorization{AllowAnonymous: true}),
	); arcErr != nil {
		return arcErr
	}
	var arcKeys5 []arcgendependencyinjection.Key
	if arcBindings.ResolveItemQueries == nil {
		arcKeys5 = append(arcKeys5, arcgendependencyinjection.KeyFor[ItemQueries]())
	}
	if arcErr := arcgenqueries.Register[Item](arcBuilder, "AllItems", arcgenqueries.Invoke(func(arcCtx arcgencontext.Context, arcInv *arcgenqueries.Invocation, arcArgs Arguments) ([]Item, error) {
		arcDependency5, arcErr := arcBindings.arcResolveItemQueries(arcCtx, arcInv.Scope())
		if arcErr != nil {
			var arcZero []Item
			return arcZero, arcErr
		}
		return (Item{}).AllItems(arcCtx, arcArgs, arcDependency5, arcInv.QueryContext(), arcInv.QueryContext().Parameters())
	}),
		arcgenqueries.WithDependencies[Arguments](arcKeys5...),
	); arcErr != nil {
		return arcErr
	}
	var arcKeys6 []arcgendependencyinjection.Key
	if arcBindings.ResolveItemQueries == nil {
		arcKeys6 = append(arcKeys6, arcgendependencyinjection.KeyFor[ItemQueries]())
	}
	if arcErr := arcgenqueries.Register[Item](arcBuilder, "Recent", arcgenqueries.Invoke(func(arcCtx arcgencontext.Context, arcInv *arcgenqueries.Invocation, arcArgs Arguments) ([]Item, error) {
		arcDependency6, arcErr := arcBindings.arcResolveItemQueries(arcCtx, arcInv.Scope())
		if arcErr != nil {
			var arcZero []Item
			return arcZero, arcErr
		}
		return RecentItems(arcCtx, arcArgs, arcDependency6)
	}),
		arcgenqueries.WithAuthorization[Arguments](arcgenmetadata.Authorization{AllowAnonymous: true}),
		arcgenqueries.WithHTTPMethod[Arguments]("QUERY"),
		arcgenqueries.WithPath[Arguments]("/generated/recent"),
		arcgenqueries.WithDependencies[Arguments](arcKeys6...),
	); arcErr != nil {
		return arcErr
	}
	return nil
}
