// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { registerHooks } from 'node:module';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import { Fields, Guid } from '@cratis/fundamentals';

const mode = process.env.ARC_COMMAND_DECORATORS ?? 'standard';
assert.ok(['standard', 'legacy'].includes(mode));
const lockedModules = new Map(['@cratis/fundamentals', '@cratis/arc/commands', '@cratis/arc/reflection', '@cratis/arc.react/commands']
    .map(specifier => [specifier, import.meta.resolve(specifier)]));
registerHooks({ resolve(specifier, context, nextResolve) {
    if (lockedModules.has(specifier)) return nextResolve(lockedModules.get(specifier), context);
    if (specifier.startsWith('.') && context.parentURL?.includes('/tsc-')) {
        const candidate = new URL(specifier + '.js', context.parentURL);
        if (existsSync(fileURLToPath(candidate))) return nextResolve(candidate.href, context);
    }
    return nextResolve(specifier, context);
} });
const { Register, Guarded, Rules, Echo, Count, Toggle, Identify, Single, Many, Numbers, Detail } = await import(
    `../../../.ai-work/output/ts-command/tsc-${mode}/Generated/Shop/Commands/index.js`);
const id = '12345678-90ab-cdef-0123-456789abcdef';
const correlationId = '00112233-4455-4677-8899-aabbccddeeff';
// Independently complete envelopes used ONLY for client-unit transport evidence.
// These are not generated by Arc and do not claim backend conformance.
function unitEnvelope(response) {
    return { correlationId, isSuccess: true, isAuthorized: true, isValid: true, hasExceptions: false,
        validationResults: [], exceptionMessages: [], exceptionStackTrace: '', authorizationFailureReason: '', response };
}
function mockFetch(t, handler) {
    const original = globalThis.fetch;
    globalThis.fetch = handler;
    t.after(() => { globalThis.fetch = original; });
}
function suppliedRegister() {
    const command = new Register();
    command.setInitialValues({ id: Guid.parse(id), name: 'name', quantity: 1, enabled: false, tags: [], 'EXACT-name': 'wire' });
    command.setOrigin('https://example.invalid');
    return command;
}
function assertEnvelope(result, expected) {
    assert.equal(result.correlationId.toString(), expected.correlationId);
    for (const key of ['isSuccess', 'isAuthorized', 'isValid', 'hasExceptions', 'exceptionMessages', 'exceptionStackTrace', 'authorizationFailureReason']) {
        assert.deepEqual(result[key], expected[key]);
    }
    assert.deepEqual(result.validationResults.map(value => ({ severity: value.severity, message: value.message, members: value.members, state: value.state })), expected.validationResults);
}

test(`${mode}: actual tsc commands keep defaults undefined, exact descriptors, Fields and setter callbacks`, () => {
    const command = new Register();
    assert.equal(command.commandName, 'Shop.Commands.Register');
    assert.equal(command.route, '/api/shop/commands/register');
    assert.deepEqual(command.roles, ['Editor', 'Admin']);
    assert.deepEqual(command.requestParameters, []);
    assert.deepEqual(command.propertyDescriptors.map(value => [value.name, value.type, value.isOptional]), [
        ['id', Guid, false], ['name', String, false], ['quantity', Number, false], ['enabled', Boolean, false],
        ['description', String, true], ['tags', String, true], ['EXACT-name', String, false]
    ]);
    assert.deepEqual(Fields.getFieldsForType(Register).map(value => [value.name, value.type, value.enumerable]), [
        ['id', Guid, false], ['name', String, false], ['quantity', Number, false], ['enabled', Boolean, false],
        ['description', String, false], ['tags', String, true], ['EXACT-name', String, false]
    ]);
    for (const descriptor of command.propertyDescriptors) assert.equal(command[descriptor.name], undefined);
    const changed = []; const owner = {};
    const callback = name => changed.push(name);
    command.onPropertyChanged(callback, owner);
    command.setInitialValues({ name: 'before', quantity: 0, enabled: false });
    assert.equal(command.hasChanges, false);
    command.name = 'after';
    assert.equal(command.hasChanges, true);
    assert.equal(changed.at(-1), 'name');
    command['EXACT-name'] = 'exact';
    assert.equal(changed.at(-1), 'EXACT-name');
    command.revertChanges();
    assert.equal(command.name, 'before');
    assert.equal(command.quantity, 0);
    assert.equal(command.enabled, false);
    assert.equal(command.hasChanges, false);
    command.clear();
    assert.equal(command.name, undefined);
    assert.equal(command.hasChanges, false);
    // Hook tuple/signature is strictly compiled. No mounted React claim here.
    assert.equal(typeof Register.use, 'function');
});

test(`${mode}: client-unit execute selects exact payload, headers, base route and complete envelope`, async t => {
    const command = suppliedRegister();
    command.setApiBasePath('/tenant');
    command.setMicroservice('orders');
    command.setHttpHeadersCallback(() => ({ 'X-Unit': 'value' }));
    command.extraneous = 'must not serialize';
    const expected = unitEnvelope(null);
    const requests = [];
    mockFetch(t, async (url, options) => {
        requests.push({ url: String(url), options });
        return Response.json(expected);
    });
    const result = await command.execute(2, true);
    assert.equal(requests.length, 1);
    const { url, options } = requests[0];
    assert.equal(url, 'https://example.invalid/tenant/api/shop/commands/register');
    assert.equal(options.method, 'POST');
    const headers = new Headers(options.headers);
    assert.equal(headers.get('Accept'), 'application/json');
    assert.equal(headers.get('Content-Type'), 'application/json');
    assert.equal(headers.get('X-Allowed-Severity'), '2');
    assert.equal(headers.get('X-Ignore-Warnings'), 'true');
    assert.equal(headers.get('X-Unit'), 'value');
    assert.deepEqual(JSON.parse(options.body), { id, name: 'name', quantity: 1, enabled: false, tags: [], 'EXACT-name': 'wire' });
    assertEnvelope(result, expected);
    assert.equal(result.response, undefined);
    assert.equal(command.hasChanges, false);
});

test(`${mode}: client-unit validate uses /validate, does not reset changes, preserves denial envelope`, async t => {
    const command = suppliedRegister(); command.name = 'changed';
    const expected = { ...unitEnvelope(null), isSuccess: false, isAuthorized: false, authorizationFailureReason: 'Server policy denies' };
    const requests = [];
    mockFetch(t, async (url, options) => {
        requests.push({ url: String(url), options });
        return Response.json(expected, { status: 403 });
    });
    const result = await command.validate();
    assert.equal(requests.length, 1);
    assert.equal(requests[0].url, 'https://example.invalid/api/shop/commands/register/validate');
    assert.equal(requests[0].options.method, 'POST');
    assert.equal(new Headers(requests[0].options.headers).get('X-Allowed-Severity'), null);
    assertEnvelope(result, expected);
    assert.equal(command.hasChanges, true);
    assert.deepEqual(command.roles, ['Editor', 'Admin']); // Hint does not override denial.
});

test(`${mode}: client validation prevents network, empty collections are present and false/zero are supplied`, async t => {
    let calls = 0;
    mockFetch(t, async () => { calls++; return Response.json(unitEnvelope(null)); });
    const missing = new Register();
    const result = await missing.execute();
    assert.equal(result.isValid, false);
    assert.equal(calls, 0);
    const command = suppliedRegister();
    command.name = '\uFEFF\u00a0 ';
    assert.equal((await command.validate()).validationResults[0].message, 'Name required');
    command.name = 'valid';
    command.quantity = 0;
    assert.equal((await command.execute()).validationResults[0].message, 'Quantity must be positive');
    command.quantity = 1;
    assert.equal((await command.execute()).isSuccess, true);
    assert.equal(calls, 1);
    const count = new Count(); count.value = 0;
    const toggle = new Toggle(); toggle.value = false;
    assert.equal(count.validateClientSide().isSuccess, true);
    assert.equal(toggle.validateClientSide().isSuccess, true);
});

test(`${mode}: inclusive warning floor cannot be relaxed through caller options`, async t => {
    let calls = 0; mockFetch(t, async () => { calls++; return Response.json(unitEnvelope(null)); });
    const command = new Guarded(); command.name = '';
    assert.equal(command.treatWarningsAsErrors, true);
    assert.equal(command.blockOnValidationSeverity, 2);
    assert.equal((await command.execute(3, true)).isSuccess, false);
    assert.equal((await command.validate()).validationResults[0].severity, 2);
    assert.equal(calls, 0);
});

test(`${mode}: bounded portable rules agree with independent shared Go corpus`, () => {
    const cases = JSON.parse(readFileSync(new URL('rule-cases.json', import.meta.url)));
    assert.equal(cases.length, 8);
    for (const entry of cases) {
        const command = new Rules();
        command.setInitialValues(entry.input);
        const results = command.validation.validate(command);
        assert.deepEqual(results.map(value => value.message), entry.messages, entry.name);
        assert.ok(results.every(value => value.severity === 3));
    }
});

test(`${mode}: client-unit actual runtime hydrates finalized scalar, model and list constructors`, async t => {
    const cases = [
        [Echo, 'text', String, false, value => assert.equal(value, 'text'), { value: 'sent' }],
        [Count, 0, Number, false, value => assert.equal(value, 0), { value: 0 }],
        [Toggle, false, Boolean, false, value => assert.equal(value, false), { value: false }],
        [Identify, id, Guid, false, value => { assert.ok(value instanceof Guid); assert.equal(value.toString(), id); }, { id: Guid.parse(id) }],
        [Single, { id, label: 'one' }, Detail, false, value => { assert.ok(value instanceof Detail); assert.ok(value.id instanceof Guid); assert.equal(value.label, 'one'); }, {}],
        [Many, [{ id, label: 'list' }], Detail, true, value => { assert.ok(Array.isArray(value)); assert.ok(value[0] instanceof Detail); assert.ok(value[0].id instanceof Guid); assert.equal(value[0].label, 'list'); }, {}],
        [Numbers, [0, -2, 3.5], Number, true, value => assert.deepEqual(value, [0, -2, 3.5]), {}]
    ];
    let expected;
    mockFetch(t, async () => Response.json(expected));
    for (const [Type, response, ctor, enumerable, check, input] of cases) {
        const command = new Type(); command.setOrigin('https://example.invalid'); command.setInitialValues(input);
        assert.equal(command._responseType, ctor); assert.equal(command._isResponseTypeEnumerable, enumerable);
        expected = unitEnvelope(response);
        const result = await command.execute();
        assertEnvelope(result, expected); check(result.response);
    }
});
